app/Http/routes.php
<?php
//URL::forceSchema('https');
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index');
Route::get('/jlt-dining-current-partners','HomeController@partners');
Route::get('/send-email','EmailController@index');
Route::get('/blog', 'BlogController@index');
Route::get('/events', 'EventController@index');
Route::get('/past-events', 'EventController@pastEvent');
Route::get('/events/{event}', 'EventController@show');
Route::get('/blog/{slug}', 'PagesController@index');
Route::resource('restaurants', 'HotelController');
Route::get('/newsletter', 'NewsletterController@index');
Route::resource('contact', 'ContactController');
Route::post('event-register','EventController@eventRegister');
//Route for special page
Route::get('festive-jlt-2019','PagesController@festiveJlt');
Route::get('restaurant/menu/{menu}','HotelController@readMenu');
Route::auth();
//Route::post('search/', 'SearchController@search');
Route::any('search/', 'SearchController@search');
Route::get('search/autocomplete', 'SearchController@autocomplete');
Route::get('feeling-hungry-and-lucky', 'SearchController@rendom_search');
Route::get('restaurants/feature/{feature}','HotelController@featurehotels');
//Route::get('/restaurant-awards-2017-nominations','AwardController@index');
//Route::get('/restaurant-awards-2018-nominations','AwardController@index');
Route::get('/restaurant-awards-2019-nominations','AwardController@index');
Route::get('/restaurant-awards-2019-voting','VotingController@index');
Route::get('/jlt-hidden-gem-2019','AwardController@hiddenGem');




Route::post('/vote/restaurant/category','VotingController@getCategoryRestaurant');
Route::post('/cast-your-vote','VotingController@store');
Route::get('/restaurateurs-login','RestaurateursLoginController@index');
Route::get('/restaurateurs-area','RestaurateursLoginController@restaurateurs_area');
Route::get('/restaurateurs-register','RestaurateursRegisterController@index');
Route::post('/restaurateurs-register','RestaurateursRegisterController@store');
/*Nominate restaurant for JLT Hidden GEM*/
Route::post('/nominate-your-restaurant','AwardController@jlt_hidden_get_nominate');
Route::post('/register-for-award','AwardController@store');
Route::get('/view_menu/{menu}','HotelController@view_menu');
/*Route::get('/jlt-hidden-gem-2018', function () {
    return redirect()->to('/restaurant-awards-2018');
});*/


Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['admin']], function () {
    Route::resource('/', 'AdminController');
    Route::post('/hotels/premium-images', 'HotelsController@premiumImages');
    // Route::get('/hotels/delete-image/{id}','HotelImagesController@destroy_image');
    Route::resource('/posts', 'PostController');
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/media', 'MediaController');
    Route::resource('/users', 'UserController');
    Route::resource('/contact', 'ContactController');
    Route::resource('/settings', 'SettingsController');
    Route::resource('/cuisines', 'CuisinesController');
    Route::resource('/dishes', 'DishesController');
    Route::resource('/features', 'FeaturesController');
    Route::resource('/meals', 'MealsController');
    Route::resource('/hotels', 'HotelsController');
    Route::post('/delete-hotel-image/', 'HotelImagesController@delete');
    Route::resource('/hotel-images', 'HotelImagesController');
    Route::resource('/tags', 'TagsController');
    Route::resource('cuisine-dishes', 'CuisineDishesController');
    Route::resource('award-category', 'AwardCategoryController');
    Route::get('award-category-restaurant/{category_id}', 'AwardCategoryController@categoryRestaurant');
    Route::post('/show-cuisine-dishes', 'CuisineDishesController@get_cuisine_dishes');
    Route::get('/delete-cuisine-dish/{id}', 'CuisineDishesController@destroy');
    Route::resource('/pages', 'PagesController');

    Route::get('event/past','EventsController@pastEvent');
    Route::resource('/events', 'EventsController');
    /*To load a cousine dishes with ajax*/
    Route::get('/show-cuisine-dishes', 'CuisineDishesController@get_cuisine_dishes');
    Route::get('/register-restaurant','AwardController@index');
    Route::get('/export-register-restaurant','AwardController@getReport');
    Route::get('/export-category-restaurant/{category_id}','AwardCategoryController@getReport');
    Route::DELETE('/register-restaurant/{id}','AwardController@destroy')->name('admin.award-user.destroy');
    Route::get('/voting-pool','VotingController@index');
    Route::get('/voting-pool/{id}','VotingController@show');
    Route::get('/votes-by-category', 'VotingController@voteByCategory');
    Route::get('/votes-by-category/top-restaurants/{category_id}', 'VotingController@restaurantTopVotes');
    Route::get('/top-restaurants-report/{category_id}', 'VotingController@topRestaurantReport');
    Route::get('/subscriber-newsletter-report', 'VotingController@subscriberReport');
    Route::resource('/offers', 'OfferController');
    Route::resource('/restaurateurs', 'RestaurateursController');
    Route::get('/jlt-hidden-gem-nominations','AwardController@pub_nomination_category');
    Route::get('/get-hidden-gem-report','AwardController@hidden_gem_report');
    Route::get('/event-participants','EventsController@getEventUsers');
});



Route::get('/{slug}', 'PagesController@index');
/*
*/
//Route::resource('blog','BlogController');

app/AwardCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AwardCategory extends Model
{
    //
    protected $table = 'awardcategory';
    protected $fillable = ['name','slug','status'];

    public function getCategoryVotes() {
        return $this->hasMany('App\Votecast','category_id');
    }

}

app/Http/Controllers/Admin/AwardCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\AwardCategory;
use App\RestaurantAawardCategory;
use App\Votecast;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Maatwebsite\Excel\Facades\Excel;

class AwardCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        $categories = AwardCategory::paginate(10);;
        return view('admin.award_category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.award_category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
           'name'  => 'required|unique:awardcategory|min:2|max:260',
        ]);
        AwardCategory::create([
            'name'   => request()->name,
            'slug' => str_slug(request()->name),
        ]);

        flash('Category was created successfully');
        return redirect()->back();


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(AwardCategory $award_category)
    {
        //
        return view('admin.award_category.edit',compact('award_category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[
            'name'  => 'required|min:2|max:260',
        ]);

        $award = AwardCategory::find($id);

        $award->name = request()->name;
        $award->slug = str_slug(request()->name);

        $award->save();
        flash('Award Category name has been updated');
        return redirect()->back();
}

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $awardCat = AwardCategory::find($id);
        $awardCat->delete();
        flash('Award Category has been deleted');
        return redirect()->back();

        //
    }

    /*
     * @param Category id
     * @retuen list of restaurant in category
     * */
    public function categoryRestaurant($category_id) {

        // Get Category Name
        $category = AwardCategory::find($category_id);
        $restaurants = RestaurantAawardCategory::select('restaurant_id')->where('category_id',$category_id)->get();
        // dd();
        return view('admin.award_category.category_restaurants',compact('restaurants','category'));
    }

    /*
     * @param request to export excel file
     * @return excel file with list of category restaurants
     * */

    public function getReport($category_id) {
        $category = AwardCategory::find($category_id);

        $restaurants = RestaurantAawardCategory::select('restaurant_id','category_id')->where('category_id',$category_id)->get();
        Excel::create(ucfirst($category->name).' Restaurants', function($excel) use ($restaurants) {
            $excel->sheet('Excel sheet', function($sheet) use ($restaurants) {
                $sheet->loadView('admin.reports.register-category-restaurant',compact('restaurants'));
                $sheet->setOrientation('landscape');
            });
        })->export('xls');
    }



}

resources/views/admin/award_category/category_restaurants.blade.php
@extends('admin.master');
@push('site_header')
        <!-- BEGIN PAGE LEVEL STYLES -->
<link href="{{asset('private/assets/global/plugins/datatables/datatables.min.css')}}" rel="stylesheet"
      type="text/css"/>
<link href="{{asset('private/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css')}}"
      rel="stylesheet" type="text/css"/>
<!-- END PAGE LEVEL STYLES -->

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="portlet-title">

            <div class="caption font-dark">
                <i class="icon-settings font-dark"></i>
                <span class="caption-subject bold uppercase"> {{'Restaurants Nominated in ' . $category->name}}</span>
            </div>
        </div>
        <div class="portlet-body">
            @if (session()->has('flash_notification.message'))
                <div class="alert alert-{{ session('flash_notification.level') }}">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {!! session('flash_notification.message') !!}
                </div>
            @endif
            <div class="table-toolbar">
                <div class="row">
                    <div class="col-md-6">
                        <div class="btn-group">
                           {{-- <a class="btn sbold green" href="{{route('admin.award-category.create')}}"><i
                                        class="fa fa-plus"></i>{{"Add New Awarad Category"}}</a>--}}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="btn-group pull-right">
                            <button class="btn green  btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                                <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">

                                <li>
                                    <a href="{{url('/admin/export-category-restaurant',$category->id)}}">
                                        <i class="fa fa-file-excel-o"></i> Export to Excel </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                <thead>


                <tr>
                    <th>SR#</th>
                    <th>
                        {{'Restaurant Name'}}
                    </th>
                    <th>
                        {{'Contact Person Name'}}
                    </th>
                    <th>
                        {{'Contact Person Phone'}}
                    </th>
                    <th>
                        {{'Contact Person Email'}}
                    </th>
                    <th>
                        {{'Votes Received'}}
                    </th>

                </tr>
                </thead>
                <tbody>

                @if(isset($restaurants) && !empty($restaurants))
                    <?php $i = 1;?>
                    @foreach($restaurants as $item)
                        <tr class="odd gradeX">
                            <td>{{$i++}}</td>


                            <td>
                                {{$item->getRestaurant->name}}
                            </td>
                            <td>
                                {{$item->getRestaurant->first_name. ' '. $item->getRestaurant->last_name}}
                            </td>

                            <td>
                                {{$item->getRestaurant->phone}}
                            </td>

                            <td>
                                {{$item->getRestaurant->email}}
                            </td>

                            <td>
                                {{$item->getRestaurant->id . '-'. $category->id}}
                            </td>


                         </tr>
                    @endforeach
                @endif
               {{-- <tr>
                    <td colspan="5">{{ $restaurants->links() }}</td>
                </tr>
--}}
                </tbody>

            </table>
        </div>

        <!-- END EXAMPLE TABLE PORTLET-->


    </div>
</div>

@endsection


@push('site_footer')
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{{asset('private/assets/pages/scripts/form-samples.min.js')}}" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
@endpush

resources/views/admin/award_category/edit.blade.php
@extends('admin.master')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>{{'Editing Award Category '.$award_category->name}}
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>
                        <a href="#portlet-config" data-toggle="modal" class="config">
                        </a>
                        <a href="javascript:;" class="reload">
                        </a>
                        <a href="javascript:;" class="remove">
                        </a>
                    </div>
                </div>
                <div class="portlet-body form">
                    <!-- BEGIN FORM-->

                    {!! Form::open(array('url' => route('admin.award-category.update',$award_category->id),'class'=>'horizontal-form','method' => 'PATCH')) !!}

                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="form-body">
                        @if (session()->has('flash_notification.message'))
                            <div class="alert alert-{{ session('flash_notification.level') }}">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                {!! session('flash_notification.message') !!}
                            </div>
                        @endif
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {!! Form::label('Category Name',null,array('class'=>'control-label')) !!}
                                    {!! Form::text('name',$award_category->name,array('class'=>'form-control','placeholder'=>'Add category name')) !!}
                                    <span class="help-block">{{'Edit Category'}} </span>
                                </div>
                            </div>
                            <!--/span-->
                            <div class="col-md-6">
                                <div class="form-group">
                                    {!! Form::label('Status',null,array('class'=>'control-label')) !!}
                                    <select name="status" class="form-control" id="status">
                                        @if(!$award_category->status=='active')
                                            <option value="0" selected>{{'Deactive'}}</option>
                                            <option value="1">{{'Active'}}</option>
                                        @else
                                            <option value="0">{{'Deactive'}}</option>
                                            <option value="1" selected>{{'Active'}}</option>
                                        @endif
                                    </select>
                                </div>
                            </div>
                            <!--/span-->
                        </div>
                    </div>
                    <div class="form-actions right">
                        <button type="button" class="btn default">Cancel</button>
                        <button type="submit" class="btn blue"><i class="fa fa-check"></i> Save</button>
                    </div>
                    {!! Form::close() !!}
                            <!-- END FORM-->
                </div>
            </div>


        </div>
    </div>

@endsection


@push('site_footer')
<script type="text/javascript"
        src="{{asset('private/assets/global/plugins/datatables/media/js/jquery.dataTables.min.js')}}"></script>
<script type="text/javascript"
        src="{{asset('private/assets/global/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js')}}"></script>
<script type="text/javascript"
        src="{{asset('private/assets/global/plugins/datatables/extensions/ColReorder/js/dataTables.colReorder.min.js')}}"></script>
<script type="text/javascript"
        src="{{asset('private/assets/global/plugins/datatables/extensions/Scroller/js/dataTables.scroller.min.js')}}"></script>

<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{{asset('private/assets/global/scripts/metronic.js')}}" type="text/javascript"></script>
<script src="{{asset('private/assets/admin/layout/scripts/layout.js')}}" type="text/javascript"></script>
<script src="{{asset('private/assets/admin/layout/scripts/quick-sidebar.js')}}" type="text/javascript"></script>
<script src="{{asset('private/assets/admin/layout/scripts/demo.js')}}" type="text/javascript"></script>
<script src="{{asset('private/assets/admin/pages/scripts/table-advanced.js')}}"></script>
<script src="{{asset('private/assets/admin/pages/scripts/components-editors.js')}}"></script>


<script src="{{asset('private/assets/global/scripts/metronic.js')}}" type="text/javascript"></script>
<script src="{{asset('private/assets/admin/layout/scripts/layout.js')}}" type="text/javascript"></script>
<script src="{{asset('private/assets/admin/layout/scripts/quick-sidebar.js')}}" type="text/javascript"></script>
<script src="{{asset('private/assets/admin/layout/scripts/demo.js')}}" type="text/javascript"></script>

<script>
    jQuery(document).ready(function () {
        Metronic.init(); // init metronic core components
        Layout.init(); // init current layout
        QuickSidebar.init(); // init quick sidebar
        Demo.init(); // init demo features
        TableAdvanced.init();
    });
</script>
@endpush

resources/views/admin/award_category/index.blade.php
@extends('admin.master');
@push('site_header')
        <!-- BEGIN PAGE LEVEL STYLES -->
<link href="{{asset('private/assets/global/plugins/datatables/datatables.min.css')}}" rel="stylesheet"
      type="text/css"/>
<link href="{{asset('private/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css')}}"
      rel="stylesheet" type="text/css"/>
<!-- END PAGE LEVEL STYLES -->

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="portlet-title">

            <div class="caption font-dark">
                <i class="icon-settings font-dark"></i>
                <span class="caption-subject bold uppercase"> {{'Award Categories Listing'}}</span>
            </div>
        </div>
        <div class="portlet-body">
            @if (session()->has('flash_notification.message'))
                <div class="alert alert-{{ session('flash_notification.level') }}">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {!! session('flash_notification.message') !!}
                </div>
            @endif
            <div class="table-toolbar">
                <div class="row">
                    <div class="col-md-6">
                        <div class="btn-group">
                            <a class="btn sbold green" href="{{route('admin.award-category.create')}}"><i
                                        class="fa fa-plus"></i>{{"Add New Award Categories"}}</a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="btn-group pull-right">
                            <button class="btn green  btn-outline dropdown-toggle" data-toggle="dropdown">Tools
                                <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li>
                                    <a href="javascript:;">
                                        <i class="fa fa-print"></i> Print </a>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        <i class="fa fa-file-pdf-o"></i> Save as PDF </a>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        <i class="fa fa-file-excel-o"></i> Export to Excel </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                <thead>

                <tr>
                    <th>SR#</th>
                    <th>
                        {{'Category Name'}}
                    </th>

                    <th>
                        {{'Category Slug'}}
                    </th>

                    <th>
                        {{'Status'}}
                    </th>
                    <th>Restaurants</th>

                    <th>
                        {{'Actions'}}
                    </th>
                </tr>
                </thead>
                <tbody>

                @if(isset($categories) && !empty($categories))
                    <?php $i = 1;?>
                    @foreach($categories as $category)
                        <tr class="odd gradeX">
                            <td>{{$i++}}</td>
                            <td>
                                {{$category->name}}
                            </td>
                            <td>
                                {{$category->slug}}
                            </td>
                            <td>
                                @if(!$category->status=='active')
                                    {{'Not Active'}}
                                @else
                                    {{'Active'}}
                                @endif

                            </td>

                            <td><a href="{{url('/admin/award-category-restaurant',$category->id)}}">View</a></td>

                            <td>
                                <div class="btn-group">
                                    <button class="btn btn-xs green dropdown-toggle" type="button"
                                            data-toggle="dropdown" aria-expanded="false"> Actions
                                        <i class="fa fa-angle-down"></i>
                                    </button>
                                    <ul class="dropdown-menu pull-left" role="menu">
                                        <li>
                                            <a href="{{route('admin.award-category.edit',$category->id)}}" class="btn btn-sm">Edit</a>
                                            {!! Form::open([
                                       'method' => 'DELETE',
                                       'route' => ['admin.award-category.destroy', $category->id]
                               ]) !!}
                                            {!! Form::submit('Delete?', ['class' => 'btn btn-sm red']) !!}
                                            {!! Form::close() !!}


                                        </li>


                                    </ul>
                                </div>


                            </td>


                        </tr>
                    @endforeach
                @endif
                <tr>
                    <td colspan="5">{{ $categories->links() }}</td>
                </tr>

                </tbody>

            </table>
        </div>

        <!-- END EXAMPLE TABLE PORTLET-->


    </div>
</div>

@endsection


@push('site_footer')
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{{asset('private/assets/pages/scripts/form-samples.min.js')}}" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
@endpush